#!/bin/sh

FILES="$(git ls-tree -l -r --name-only HEAD .)"
MAXLEN=0
IFS="$(printf "\n\b")"
for f in $FILES; do
    if [ ${#f} -gt $MAXLEN ]; then
        MAXLEN=${#f}
    fi
done
for f in $FILES; do
    str="$(git log -1 --pretty=format:"%cd %h %cn" $f)"
    printf "%-${MAXLEN}s -- %s\n" "$f" "$str"
done
